### ISSUE TITLE
Weak documentation

### ISSUE THREAD

**Issue by OleksandrRabchuk** [palkeo/panoramix#29]
Hi, can you pls provide some documentation on how to get an output from **panoramix**. I am using **subprocess** to run the command, and wanting to retrieve decompiled functions form it. Everything is ok except I am getting some strange output.

Code:
```python
@app.route("/", methods=["POST"])
def index():
    try:
        data = flask.request.json
        address = data['address']
        process = subprocess.run(['panoramix', address], capture_output=True)
        print(process)
        return address
    except Exception as e:
        return flask.Response(status=400)
```
Output I want:

Output I get:

```
CompletedProcess(args=['panoramix', '0x06012c8cf97bead5deae237070f9587f8e7a266d'], returncode=1, stdout=b'', stderr=b'13:09:54 panoramix.loader Fetching code for 0x06012c8cf97bead5deae237
070f9587f8e7a266d...\nTraceback (most recent call last):\n  File "/app/.heroku/python/bin/panoramix", line 8, in <module>\n    sys.exit(main())\n  File "/app/.heroku/python/lib/python3.10/site-packages/panoramix/__main__.py", line 1
13, in main\n    print_decompilation(sys.argv[1])\n  File "/app/.heroku/python/lib/python3.10/site-packages/panoramix/__main__.py", line 79, in print_decompilation\n    decompilation = decompile_address(this_addr, function_name)\n  
File "/app/.heroku/python/lib/python3.10/site-packages/panoramix/decompiler.py", line 50, in decompile_address\n    loader.load_addr(address)\n  File "/app/.heroku/python/lib/python3.10/site-packages/panoramix/loader.py", line 103, 
in load_addr\n    code = w3.eth.getCode(Web3.toChecksumAddress(address)).hex()[2:]\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/module.py", line 57, in caller\n    result = w3.manager.request_blocking(method_str,\n
  File "/app/.heroku/python/lib/python3.10/site-packages/web3/manager.py", line 197, in request_blocking\n    response = self._make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/manager.py", 
line 150, in _make_request\n    return request_func(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware\n    response = make_request(method, params)\n  Fil
e "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware\n    return make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/fo
rmatting.py", line 94, in middleware\n    response = make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware\n    response = make_request(method, pa
rams)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware\n    response = make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middl
eware/formatting.py", line 94, in middleware\n    response = make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware\n    response = make_request(
method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware\n    return make_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-pa
ckages/web3/providers/auto.py", line 94, in make_request\n    return self._proxy_request(method, params)\n  File "/app/.heroku/python/lib/python3.10/site-packages/web3/providers/auto.py", line 106, in _proxy_request\n    raise Canno
tHandleRequest(\nweb3.exceptions.CannotHandleRequest: Could not discover provider while making request: method:eth_getCode\nparams:[\'0x06012c8cf97BEaD5deAe237070F9587f8E7A266d\', \'latest\']\n\n')
```

**Comment by palkeo** [comment]
It needs to have access to an Ethereum nodepointed by WEB3_PROVIDER_URI. Also I recommend using panoramix as a Python library (instead of a subprocess) for your use case.
