### ISSUE TITLE
HASH: Out of overflow pages.  Increase page size

### ISSUE THREAD

**Issue by mafangtao** [palkeo/panoramix#53]
panoramix 0x9Db7378614d8d9D7149c4eE4763F88c38F9B1517

---->

Traceback (most recent call last):
  File "/opt/homebrew/bin/panoramix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/__main__.py", line 79, in main
    print_decompilation(args.address_or_bytecode, args)
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/__main__.py", line 51, in print_decompilation
    decompilation = decompile_address(this_addr, function_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/decompiler.py", line 51, in decompile_address
    return _decompile_with_loader(loader, only_func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/decompiler.py", line 123, in _decompile_with_loader
    loader.run(VM(loader, just_fdests=True))
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/loader.py", line 137, in run
    make_abi(self.hash_targets)
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/utils/signatures.py", line 159, in make_abi
    sig = fetch_sig(h)
          ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/utils/helpers.py", line 151, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/utils/supplement.py", line 68, in fetch_sig
    check_supplements()
  File "/opt/homebrew/lib/python3.11/site-packages/panoramix/utils/supplement.py", line 59, in check_supplements
    out[selector] = abi
    ~~~^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_dbm.error: cannot add item to database

**Comment by romanR1H2** [comment]
U

**Comment by radiofreejohn** [comment]
Not sure what platform you are on but the following worked for me:

1. delete the cache file (it appears above the trace for me
```
2023-08-03 16:24:24,678 haruspex.local panoramix.utils.supplement[17763] INFO Loading /opt/homebrew/lib/python3.11/site-packages/panoramix/data/abi_dump.xz into /Users/john/Library/Caches/panoramix/abi_db.shelve...
```
Here the file is `/Users/john/Library/Caches/panoramix/abi_db.shelve.db` yours may be different.

2. Install pythong-gdbm
I'm using Homebrew, so it was just `brew install python-gdbm`

After that the program ran fine.
