### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by guange2015** [palkeo/panoramix#61]
(venv) root@ccedc66751ef:~# panoramix  0x608060405234801561001057600080fd5b506004361061004c5760003560e01c806312424e3f14610051578063485cc9551461005b578063a98ad46c1461006e578063ea5a94511461009d575b600080fd5b6100596100b0565b005b610059610069366004610282565b61013c565b600054610081906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b600154610081906001600160a01b031681565b60005460015460405163095ea7b360e01b81526001600160a01b039182166004820152600019602482015291169063095ea7b390604401602060405180830381600087803b15801561010157600080fd5b505af1158015610115573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101399190610259565b50565b6000546001600160a01b0316156101905760405162461bcd60e51b81526020600482015260146024820152731a185cc81899595b881a5b9a5d1a585b1a5e995960621b604482015260640160405180910390fd5b600080546001600160a01b038481166001600160a01b031992831681179093556001805491851691909216811790915560405163095ea7b360e01b81526004810191909152600019602482015263095ea7b390604401602060405180830381600087803b15801561020057600080fd5b505af1158015610214573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906102389190610259565b505050565b80356001600160a01b038116811461025457600080fd5b919050565b60006020828403121561026b57600080fd5b8151801515811461027b57600080fd5b9392505050565b6000806040838503121561029557600080fd5b61029e8361023d565b91506102ac6020840161023d565b9050925092905056fea2646970667358221220c266ebfb30e19154d308f53792ac0de7308c65a210a9175fa1b8d35634b6338d64736f6c63430008070033

2023-06-21 19:56:08,285 ccedc66751ef panoramix.decompiler[252114] INFO Running light execution to find functions.
2023-06-21 19:56:08,287 ccedc66751ef panoramix.utils.supplement[252114] INFO Loading /root/.python/venv/lib/python3.11/site-packages/panoramix/data/abi_dump.xz into /root/.cache/panoramix/abi_db.shelve...
Traceback (most recent call last):
  File "/root/.python/venv/bin/panoramix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/__main__.py", line 79, in main
    print_decompilation(args.address_or_bytecode, args)
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/__main__.py", line 53, in print_decompilation
    decompilation = decompile_bytecode(this_addr, function_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/decompiler.py", line 45, in decompile_bytecode
    return _decompile_with_loader(loader, only_func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/decompiler.py", line 123, in _decompile_with_loader
    loader.run(VM(loader, just_fdests=True))
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/loader.py", line 137, in run
    make_abi(self.hash_targets)
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/utils/signatures.py", line 159, in make_abi
    sig = fetch_sig(h)
          ^^^^^^^^^^^^
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/utils/helpers.py", line 151, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/utils/supplement.py", line 68, in fetch_sig
    check_supplements()
  File "/root/.python/venv/lib/python3.11/site-packages/panoramix/utils/supplement.py", line 61, in check_supplements
    assert abi_path().is_file()
AssertionError

**Comment by tadhglooram93** [comment]
been having the same issues, would also like some help

**Comment by dinhln89** [comment]
same error :(
